name: nicoledechow
favicon: null
layout_spectrum: 0.3255153058562428
typography_spectrum: 0.8736512830946594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#91d7bb'
    - '#e1f3eb'
    - '#ade1cb'
    - '#d1ede1'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.6123440400697291
  rhythmicContrast: 0.498690984910354
purpose: []
